### ISSUE TITLE
Nmap

### ISSUE THREAD

**Issue by c4ndies** [hobbsh/icinga-autod#2]
new version of nmap seems to not be compatible with you script. Which latest version of nmap do you use? Thanks

**Comment by hobbsh** [comment]
Can you please post some debug output? Thanks

**Comment by c4ndies** [comment]
Hi, I hope I'm doing it correctly. Cordialement,
Jules CHABRIERDUT Réseaux Et Télécoms IUT La Rochelle
http://www.iut-larochelle.fr/iut-la-rochelle/departement-reseaux-et-telecommunications


      De : Wylie Hobbs <notifications@github.com>
 À : hobbsh/icinga2-autod <icinga2-autod@noreply.github.com> 
Cc : c4ndies <julechab@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Jeudi 30 juin 2016 7h12
 Objet : Re: [hobbsh/icinga2-autod] Nmap (#2)
   
Can you please post some debug output? Thanks—

**Comment by hobbsh** [comment]
What is the output of `nmap --version`?

Also, what is the output of the script run with -d True (debug)

**Comment by c4ndies** [comment]
Hope i didn't mistake myself with the parameters Cordialement,
Jules CHABRIERDUT Réseaux Et Télécoms IUT La Rochelle
http://www.iut-larochelle.fr/iut-la-rochelle/departement-reseaux-et-telecommunications


      De : Wylie Hobbs <notifications@github.com>
 À : hobbsh/icinga2-autod <icinga2-autod@noreply.github.com> 
Cc : c4ndies <julechab@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Jeudi 30 juin 2016 8h57
 Objet : Re: [hobbsh/icinga2-autod] Nmap (#2)
   
What is the output of nmap --version?Also, what is the output of the script run with -d True (debug)—

**Comment by hobbsh** [comment]
I realize there's probably a language barrier but if you want help can you please fully understand my questions/requests and post the appropriate output? Thank you. 

Je me rends compte qu'il ya probablement une barrière de la langue , mais si vous voulez de l'aide pouvez-vous s'il vous plaît comprendre mes questions / demandes et après la sortie appropriée ?

**Comment by c4ndies** [comment]
Ok, I've just realised that I was sending you screenshots of outputs via email when answering to your requests but it doesn't appears on git...
![capture](https://cloud.githubusercontent.com/assets/19549646/16482439/a1f902b2-3ea7-11e6-9c0d-4191639a8c04.PNG)

**Comment by hobbsh** [comment]
No problem, sorry for the misunderstanding. Thanks for posting your output. You need to use CIDR notation when specifying the network to scan. So your command should be:

`./icinga-autod.py -n 192.168.1.0/24`

**Comment by c4ndies** [comment]
Thanks for the fast answer! I was putting a spacebar between ip address and mask...
Sorry for wasting your time.

**Comment by hobbsh** [comment]
Happy to help and glad you have a use for icinga-autod! Thanks for using it!
